### PR TITLE
Feat: With jokes recyclerview

### PR DESCRIPTION
**Pull request by DaChelimo**
Gets jokes from open-source API and displays the jokes in a recyclerview.

Also includes joke liking and changed application ID to match package name.

### CODE REVIEW

**Comment by DaChelimo** [comment]
Anyone with access to the Firebase project kindly change the application Id then send us the updated google-services.json . 
The jokes functionality isn't over yet but I decided to push so that you guys can have a rough idea of what was on my mind. If you have ideas on possible modifications, kindly comment below.

**Comment by Andre-max** [comment]
Reopen PR

**Comment by Andre-max** [comment]
Y

**Review by daniel-waiguru — COMMENTED** [review]
Lift the database query tasks out of the main thread

**Pull request closed without merging**
